<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ActivityLog;
use App\Models\Customer;
use App\Models\Task;
use App\Models\User;

class AnalyticsController extends Controller
{
    public function index()
    {
        return view('admin.analytics.index');
    }

    public function exportCsv()
    {
        $headers = [
            'Content-type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename=veltrix_intelligence_report_' . date('Y-m-d_H-i-s') . '.csv',
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0'
        ];

        $callback = function() {
            $file = fopen('php://output', 'w');

            // 1. Title Banner
            fputcsv($file, ['=========================================================']);
            fputcsv($file, ['        VELTRIX CRM - BUSINESS INTELLIGENCE EXPORT       ']);
            fputcsv($file, ['=========================================================']);
            fputcsv($file, ['Generated At', date('Y-m-d H:i:s')]);
            fputcsv($file, ['Generated By', auth()->user()->name . ' (Administrator)']);
            fputcsv($file, []);

            // 2. Summary Stats
            $totalCustomers = Customer::count();
            $totalTasks = Task::count();
            $totalStaff = User::where('role', 'staff')->count();
            $completedTasks = Task::where('status', 'completed')->count();
            $completionRate = $totalTasks > 0 ? round(($completedTasks / $totalTasks) * 100, 1) . '%' : '0%';

            fputcsv($file, ['[1. EXECUTIVE SUMMARY]']);
            fputcsv($file, ['Metric', 'Value']);
            fputcsv($file, ['Total Registered Customers', $totalCustomers]);
            fputcsv($file, ['Total Operational Tasks', $totalTasks]);
            fputcsv($file, ['Total Active Staff', $totalStaff]);
            fputcsv($file, ['Task Completion Efficiency', $completionRate]);
            fputcsv($file, []);

            // 3. Customer Segments
            $leadsCount = Customer::where('status', 'lead')->count();
            $activeCustomersCount = Customer::where('status', 'active')->count();
            $inactiveCustomersCount = Customer::where('status', 'inactive')->count();

            fputcsv($file, ['[2. CUSTOMER ENTITY DISTRIBUTION]']);
            fputcsv($file, ['Segment / Status', 'Total Count']);
            fputcsv($file, ['Leads / Prospects', $leadsCount]);
            fputcsv($file, ['Active Customers', $activeCustomersCount]);
            fputcsv($file, ['Inactive Accounts', $inactiveCustomersCount]);
            fputcsv($file, []);

            // 4. Task Velocity
            $pendingTasksCount = Task::where('status', 'pending')->count();
            $inProgressTasksCount = Task::where('status', 'in_progress')->count();

            fputcsv($file, ['[3. OPERATIONAL VELOCITY]']);
            fputcsv($file, ['Task Status', 'Total Count']);
            fputcsv($file, ['Pending Status', $pendingTasksCount]);
            fputcsv($file, ['In Progress Status', $inProgressTasksCount]);
            fputcsv($file, ['Completed Status', $completedTasks]);
            fputcsv($file, []);

            // 5. Staff Performance Workload
            $staffs = User::where('role', 'staff')->withCount(['customers', 'tasks'])->get();
            fputcsv($file, ['[4. STAFF PERFORMANCE & WORKLOAD FLOW]']);
            fputcsv($file, ['Staff Member Name', 'Assigned Customers', 'Assigned Tasks', 'Total Score']);
            foreach ($staffs as $staff) {
                fputcsv($file, [
                    $staff->name,
                    $staff->customers_count,
                    $staff->tasks_count,
                    $staff->customers_count + $staff->tasks_count
                ]);
            }
            fputcsv($file, []);

            // 6. Activity Pulse Logs
            $logs = ActivityLog::with('user')->latest()->take(25)->get();
            fputcsv($file, ['[5. IMMUTABLE ACTIVITY Pulse (AUDIT TRAILS)]']);
            fputcsv($file, ['Timestamp', 'Personnel', 'Operation/Action', 'Parameter Detail']);
            foreach ($logs as $log) {
                fputcsv($file, [
                    $log->created_at->toDateTimeString(),
                    $log->user->name ?? 'System',
                    $log->action,
                    $log->description
                ]);
            }

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    public function getData()
    {
        $customerStats = [
            'lead' => Customer::where('status', 'lead')->count(),
            'active' => Customer::where('status', 'active')->count(),
            'inactive' => Customer::where('status', 'inactive')->count(),
        ];

        $taskStats = [
            'pending' => Task::where('status', 'pending')->count(),
            'in_progress' => Task::where('status', 'in_progress')->count(),
            'completed' => Task::where('status', 'completed')->count(),
        ];

        $recentLogs = ActivityLog::with('user')->latest()->take(10)->get();

        return response()->json([
            'customerStats' => $customerStats,
            'taskStats' => $taskStats,
            'recentLogs' => $recentLogs
        ]);
    }

    public function clearLogs()
    {
        ActivityLog::truncate();
        return response()->json(['success' => true]);
    }
}
